### ISSUE TITLE
Delete from UI does not work on Windows

### ISSUE THREAD

**Issue by basrijn** [crewtimer/crewtimer-video-review#36]
When trying to delete a file from the File selector on the ride side of the UI., it does not actually delete the file:

```
delete R:\2024 - BC Champs\20240712\20240712_160221.mp4 selectedIndex: 0 id: 0
FileList.tsx:83 Uncaught TypeError: (0 , m.moveToFileIndex) is not a function
    at Object.handleConfirm (FileList.tsx:83:11)
    at onClick (ConfirmDialog.tsx:84:18)
    at Object.we (react-dom.production.min.js:54:317)
    at De (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at _o (react-dom.production.min.js:105:68)
    at ko (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at il (react-dom.production.min.js:274:42)
    at Te (react-dom.production.min.js:52:375)
```

**Comment by basrijn** [comment]
The file delete now works, but I think it does not update the top file bar to reflect the removal. I have to do some more testing

**Comment by glenne** [comment]
Hi Bas,  See #30.  This may be what you are experiencing.
